### ISSUE TITLE
License

### ISSUE THREAD

**Issue by L4Ph** [speedypotato/Pocket-SDVX#3]
What about licensing?
I would like to sell my products(actual store) in stores, so I'm wondering if I can use this service.
If it is (no license), I would like to see a statement to that effect (or a tag).

**Comment by speedypotato** [comment]
Technically, the readme states the licensing: This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

However if you ask, I generally give permission to people to sell the Pocket SDVX as long as they disclose any parts which are different from the original list.  So since you asked here, you can sell as long as you comply with the previous statement.  Thanks!
